# Generated by Django 3.2.6 on 2021-08-21 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(default='')),
                ('facultyname', models.CharField(default='', max_length=50)),
                ('dept', models.CharField(default='', max_length=50)),
                ('add', models.CharField(default='', max_length=50)),
                ('mobile', models.BigIntegerField(default='')),
                ('username', models.CharField(default='', max_length=50)),
                ('password', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
