# Generated by Django 3.2.6 on 2021-09-04 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lib',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lib_code', models.IntegerField(default='')),
                ('lname', models.CharField(default='', max_length=50)),
                ('add', models.CharField(default='', max_length=50)),
                ('mob', models.BigIntegerField(default='')),
                ('pincode', models.CharField(default='', max_length=50)),
                ('email', models.CharField(default='', max_length=50)),
                ('username', models.CharField(default='', max_length=50)),
                ('password', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
