# Generated by Django 3.2.6 on 2021-08-21 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('admno', models.BigIntegerField(default='')),
                ('rollno', models.BigIntegerField(default='')),
                ('college', models.CharField(default='', max_length=50)),
                ('parentname', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
